// Kamus dwibahasa (ID/EN). File ini aman dipakai di komponen server MAUPUN client.
// String dengan placeholder memakai pola {nama} dan diisi lewat fill().

export function fill(str, vars) {
  return String(str ?? "").replace(/\{(\w+)\}/g, (_, k) => (vars?.[k] ?? `{${k}}`));
}

export const dict = {
  id: {
    common: {
      copy: "Salin",
      copied: "Tersalin",
    },
    header: {
      catalog: "Katalog",
      howTo: "Cara Sewa",
      reports: "Akun Bermasalah",
      login: "Masuk",
      rentNow: "Sewa sekarang",
      rent: "Sewa",
    },
    footer: {
      tagline: "Rental akun Mobile Legends online. Buka 24 jam, setiap hari.",
      contact: "Kontak",
      reports: "Akun Bermasalah",
      disclaimer:
        "Rentzo tidak berafiliasi dengan Moonton. Mobile Legends dan seluruh merek terkait milik pemiliknya masing-masing.",
    },
    home: {
      available: "{n} akun siap dimainkan",
      heroTitle1: "Pilih akun.",
      heroTitle2: "Langsung main.",
      heroSummary:
        "Sewa akun Mobile Legends rank tinggi dan full skin. Proses cepat, akun aman, waktu main tidak dibagi.",
      seeAll: "Lihat semua akun",
      howTo: "Cara menyewa",
      ready: "Siap",
      rented: "Disewa",
      heroesSkins: "{heroes} hero / {skins} skin",
      perHour: "/jam",
      emptyDeck: "Katalog akun segera tersedia.",
      collectionEyebrow: "Koleksi Rentzo",
      catalogTitle: "Katalog akun",
      catalogDesc:
        "Setiap akun dicek admin sebelum disewakan. Email dan password akun baru terlihat setelah pembayaranmu terkonfirmasi.",
      liveNow: "{n} LIVE sekarang",
      howEyebrow: "Mulai bermain",
      howTitle: "Cara Sewa",
      howDesc: "Tiga langkah, biasanya selesai kurang dari lima menit.",
      steps: [
        { title: "Pilih akun", desc: "Telusuri katalog, cek rank, skin, dan harganya. Semua info ditulis apa adanya." },
        { title: "Bayar", desc: "Isi form sewa, transfer sesuai total, lalu kirim bukti ke admin lewat Telegram." },
        { title: "Login dan main", desc: "Setelah pembayaran terkonfirmasi, email dan password akun tampil di halaman order." },
      ],
      serviceTitle: "Bukan cuma janji aman.",
      serviceDesc: "Ini aturan yang kami jalankan pada setiap akun dan setiap sesi sewa.",
      perks: [
        { metric: "100%", title: "Waktu main tetap utuh", desc: "Tidak bisa login atau akun bermasalah? Durasi yang hilang kami kembalikan penuh." },
        { metric: "Milik kami", title: "Bukan akun titipan", desc: "Setiap akun dikelola langsung oleh Rentzo. Tidak ada akun curian, phishing, atau sumber yang tidak jelas." },
        { metric: "<5 menit", title: "Admin benar-benar merespons", desc: "Dukungan tersedia 24 jam dengan rata-rata balasan di bawah lima menit." },
        { metric: "1 : 1", title: "Tidak berbagi sesi", desc: "Satu akun hanya untuk satu penyewa. Password selalu diganti setelah masa sewa selesai." },
      ],
      ctaTitle: "Mau main hari ini?",
      ctaDesc: "Slot weekend cepat habis. Amankan akunmu dari sekarang, bayar setelah deal dengan admin.",
      ctaBtn: "Chat admin sekarang",
      ctaWa: "Halo min, saya mau sewa akun Mobile Legends hari ini",
    },
    card: {
      subtitle: "Rental akun Mobile Legends",
      from: "Mulai dari",
      perHour: "per jam",
      available: "Tersedia",
      rented: "Sedang disewa",
      heroes: "{n} hero",
      skins: "{n} skin",
      rent: "Sewa",
      rentedBtn: "Disewa",
      viewDetail: "Lihat detail {title}",
    },
    showcase: {
      aria: "Pilihan akun rental",
      kickerReady: "AKUN TERSEDIA SEKARANG",
      kickerRented: "AKUN SEDANG DISEWA",
      desc: "Rank {rank} dengan {heroes} hero dan {skins} skin. Siap dipakai untuk push rank dan mabar.",
      rankFallback: "tinggi",
      perHour: "/ jam",
      rent: "Sewa akun",
      detail: "Lihat detail",
      available: "Tersedia",
      rented: "Sedang disewa",
      perHourShort: "/jam",
      showAccount: "Tampilkan {title}",
    },
    filter: {
      title: "Filter rank",
      all: "Semua",
      found: "{n} akun ditemukan",
      live: "Sedang LIVE",
      offline: "Offline",
      empty: "Belum ada akun di kategori ini. Coba kategori lain atau chat admin.",
      groupLabel: "Filter rank",
    },
    akun: {
      home: "Beranda",
      catalog: "Katalog",
      noPreview: "Preview belum tersedia",
      aboutEyebrow: "Tentang akun",
      aboutTitle: "Yang kamu dapatkan",
      defaultDesc: "Informasi lengkap akun telah diverifikasi oleh admin sebelum ditampilkan di katalog.",
      feature1: "Data login privat",
      feature2: "Dicek sebelum sewa",
      feature3: "Garansi kendala login",
      dossier: "Account dossier",
      rankNow: "Rank saat ini",
      heroesAvail: "Hero tersedia",
      skinColl: "Koleksi skin",
      accLevel: "Level akun",
      from: "Mulai dari",
      perHour: "/jam",
      minHours: "Min. 1 jam",
      maxHours: "Maks. 72 jam",
      bookingNote:
        "Data login muncul setelah pembayaran terkonfirmasi. Hanya kamu yang memegang akun selama masa sewa.",
      rentThis: "Sewa akun ini",
      rentedBtn: "Sedang disewa",
      rentedNote:
        "Akun ini sedang dipakai penyewa lain. Cek akun lain di katalog atau tanya admin untuk jadwal kosong.",
      tierLabel: "Tier akun",
    },
    sewa: {
      title: "Form sewa",
      sub: "Isi data di bawah, lalu kamu dapat kode order untuk pembayaran.",
      rentedTitle: "Akun sedang disewa",
      rentedDesc: "{title} sedang dipakai penyewa lain. Pilih akun lain yang masih tersedia.",
      back: "Kembali ke katalog",
    },
    checkout: {
      name: "Nama kamu",
      namePh: "contoh: Raka",
      wa: "Nomor WhatsApp aktif",
      waPh: "contoh: 081234567890",
      voucher: "Kode voucher marketer (opsional)",
      voucherPh: "contoh: RAKA10",
      voucherHint: "Punya kupon dari marketer? Masukkan di sini untuk bonus masa aktif sewa +{days} hari, gratis.",
      noAccount: "Belum punya akun?",
      register: "Daftar",
      noAccountTail: "agar order tersimpan di profilmu.",
      duration: "Pilih durasi sewa",
      currency: "Pilih mata uang",
      curIdr: "Rupiah (Rp)",
      curUsd: "Dollar (USD)",
      curUsdHint: "Untuk pembeli luar negeri. Pembayaran dilakukan via crypto (BTC, USDT, dll).",
      usdUnavailable: "Belum tersedia (USD)",
      curPayNote: "Order ini dibayar via crypto dalam USD.",
      perHour: "Per jam",
      perHourUnit: "/jam",
      hoursAria: "Durasi sewa dalam jam",
      hoursHint: "Minimal 1 jam, maksimal 72 jam.",
      package: "Paket {label}",
      save: "hemat {amount}",
      total: "Total bayar",
      submit: "Buat order",
      submitting: "Membuat order...",
      hours: "{n} jam",
      days: "{n} hari",
      weeks: "{n} minggu",
    },
    order: {
      codeLabel: "Kode order",
      account: "Akun",
      renter: "Penyewa",
      duration: "Durasi",
      created: "Dibuat",
      total: "Total",
      pkg: "Paket {label}",
      hours: "{n} jam",
      bonusLine: "+{days} hari bonus kupon {code}",
      pendingTitle: "Selesaikan pembayaran",
      pendingDesc:
        "Bayar lewat QRIS atau virtual account bank. Setelah pembayaran berhasil, email dan password akun otomatis muncul di halaman ini.",
      pendingUsdDesc:
        "Bayar via crypto (BTC, USDT, dll) dalam USD. Setelah pembayaran berhasil, email dan password akun otomatis muncul di halaman ini.",
      pay: "Bayar {total}",
      cryptoPay: "Bayar dengan Crypto (BTC, USDT, dll)",
      cryptoLoading: "Menyiapkan invoice crypto...",
      autoCheck:
        "Status dicek otomatis setiap beberapa detik — halaman ini berubah sendiri begitu pembayaranmu terkonfirmasi.",
      processedPakasir: "Pembayaran diproses oleh Pakasir.",
      processedBoth: "Pembayaran diproses oleh Pakasir atau OxaPay.",
      needHelp: "Ada kendala?",
      chatAdmin: "Chat admin",
      waIssue: "Halo min, ada kendala pembayaran order {code}",
      paidTitle: "Akun kamu siap",
      paidDesc:
        "Login pakai data di bawah. Durasi {duration} dihitung sejak kamu login. Jangan ganti password akun.",
      paidBonus: "Kupon {code} berhasil dipakai — masa aktif sewamu diperpanjang {days} hari gratis.",
      emailAcc: "Email akun",
      password: "Password",
      contactAdmin: "Hubungi admin",
      loginIssue: "Ada masalah saat login?",
      waLogin: "Halo min, ada kendala login untuk order {code}",
      doneTitle: "Sewa selesai",
      doneDesc: "Terima kasih sudah menyewa di Rentzo. Akun sudah kami amankan kembali.",
      rentAgain: "Sewa lagi",
      cancelTitle: "Order dibatalkan",
      cancelDesc: "Order ini tidak aktif. Kalau kamu merasa ini keliru, hubungi admin.",
      askAdmin: "Tanya admin",
      waCancel: "Halo min, saya mau tanya soal order {code} yang dibatalkan",
      durationPkg: "paket {label}",
      bonusConcat: " + bonus {days} hari dari kupon {code}",
      remaining: "Sisa masa sewa",
      remainingEnded: "Masa sewa sudah berakhir",
      remainingUntil: "Berakhir {date}",
    },
    profil: {
      hello: "Halo, {name}!",
      sub: "Ini akunmu di Rentzo.",
      logout: "Keluar",
      name: "Nama",
      email: "Email",
      wa: "WhatsApp",
      since: "Terdaftar sejak",
      explore: "Jelajahi katalog & sewa akun",
      history: "Riwayat order",
      empty: "Kamu belum punya order. Mulai sewa akun pertama lewat katalog.",
      thCode: "Kode",
      thAccount: "Akun",
      thDuration: "Durasi",
      thTotal: "Total",
      thStatus: "Status",
      pkg: "Paket {label}",
      hours: "{n} jam",
      bonus: "+{days} hari kupon {code}",
      sisa: "Sisa {value}",
    },
    auth: {
      eyebrow: "Ruang mainmu menunggu",
      title: "Main tanpa batas.",
      summary:
        "Masuk ke Rentzo untuk melanjutkan sesi rental, melihat order, dan mengakses akun yang sedang kamu sewa.",
      trust1: "Akun terverifikasi",
      trust2: "Data login aman",
      notMember: "BELUM MEMBER?",
      register: "Daftar",
      welcome: "Selamat datang kembali",
      loginTitle: "Masuk ke akunmu",
      loginSub: "Lanjutkan petualanganmu di Land of Dawn.",
      email: "Email",
      emailPh: "nama@email.com",
      password: "Password",
      passwordPh: "Masukkan password",
      loginBtn: "Masuk ke Rentzo",
      checking: "Memeriksa...",
      caption: "Dengan masuk, kamu menyetujui penggunaan layanan Rentzo.",
      regTitle: "Buat akun",
      regSub: "Daftar gratis untuk menyewa akun di Rentzo.",
      haveAccount: "Sudah punya akun?",
      loginHere: "Masuk",
      loginHereLong: "Masuk di sini",
      name: "Nama",
      namePh: "Nama lengkap atau nickname",
      regEmailPh: "kamu@contoh.com",
      wa: "Nomor WhatsApp",
      passMinPh: "Minimal 6 karakter",
      confirm: "Ulangi password",
      confirmPh: "Ketik ulang password",
      regBtn: "Daftar",
      regLoading: "Mendaftarkan...",
    },
    marketer: {
      loginTitle: "Area marketer",
      loginSub: "Masuk untuk memantau performa kuponmu. Belum punya akun? Minta admin mendaftarkanmu.",
      loginBtn: "Masuk ke dashboard",
      hello: "Halo, {name}!",
      sub: "Pantau performa kuponmu dan buat kode baru kapan saja.",
      logout: "Keluar",
      statActive: "Kupon aktif",
      statUsed: "Total pemakaian kupon",
      statBonus: "Bonus per pemakaian",
      bonusDaysValue: "+{days} hari",
      statCommission: "Komisi saya",
      statCommissionUsd: "Komisi Dollar",
      createTitle: "Buat kode kupon baru",
      createDesc:
        "Setiap penyewa yang memasukkan kodemu saat checkout dapat bonus masa aktif sewa +{days} hari, gratis. Bagikan kodenya di konten, status WA, atau ke teman langsung.",
      createPh: "contoh: RAKAHEMAT — kosongkan untuk kode acak",
      createBtn: "Buat kupon",
      creating: "Membuat...",
      yourCoupons: "Kupon kamu",
      noCoupons: "Kamu belum punya kupon. Buat kode pertamamu di atas.",
      active: "Aktif",
      inactive: "Nonaktif",
      createdAt: "Dibuat {date}",
      usedTimes: "{n}x dipakai",
      deactivate: "Nonaktifkan",
      activate: "Aktifkan",
      delete: "Hapus",
      deleteMsg: "Hapus kupon {code}? Kode ini tidak bisa dipakai penyewa lagi. Riwayat pemakaian tetap tersimpan.",
      usageTitle: "Akun yang disewa pakai kuponmu",
      noUsage: "Belum ada penyewa yang memakai kuponmu.",
      thOrder: "Kode order",
      thAccount: "Akun disewa",
      thCoupon: "Kupon",
      thBonus: "Bonus",
      thStatus: "Status",
      thCommission: "Komisi",
    },
    status: {
      ready: "LIVE · Tersedia",
      rented: "Sedang disewa",
      maintenance: "Perawatan",
      pending: "Menunggu pembayaran",
      paid: "Lunas",
      done: "Selesai",
      cancelled: "Dibatalkan",
    },
    reports: {
      eyebrow: "Peringatan untuk pembeli akun",
      title: "Daftar akun bermasalah",
      desc: "Daftar akun yang dilaporkan hackback, ganti password, atau penipuan oleh pembeli nyata. Cek dulu ID akunnya di sini sebelum beli akun dari siapa pun.",
      statsTotal: "Total laporan",
      statsVerified: "Terverifikasi",
      statsPending: "Menunggu verifikasi",
      searchLabel: "Cari ID akun, nickname, atau penjual",
      searchPh: "contoh: 123456789",
      filterAll: "Semua kasus",
      typeHackback: "Hackback",
      typePassword: "Ganti password",
      typeScam: "Penipuan",
      typeOther: "Lainnya",
      found: "{n} laporan",
      empty: "Tidak ada laporan yang cocok. Coba kata kunci atau filter lain.",
      emptyAll: "Belum ada laporan terverifikasi. Kalau kamu pernah ditipu, jadilah yang pertama melapor.",
      accountId: "ID akun",
      server: "Server",
      nickname: "Nickname",
      seller: "Penjual",
      sellerContact: "Kontak penjual",
      game: "Game",
      evidence: "Lihat bukti",
      reportedAt: "Dilaporkan {date}",
      ctaTitle: "Pernah ketiban akun hackback?",
      ctaDesc: "Bagikan pengalamanmu supaya pembeli lain tidak jadi korban berikutnya. Laporan tampil di daftar setelah dicek admin.",
      ctaBtn: "Laporkan akun sekarang",
      formTitle: "Laporkan akun bermasalah",
      formSub: "Isi data akun yang bermasalah sebisa kamu. Semua laporan dicek admin sebelum dipajang di daftar.",
      gameLabel: "Game akun",
      idLabel: "ID akun in-game",
      idPh: "contoh: 123456789",
      zoneLabel: "Server / Zone ID (opsional)",
      zonePh: "contoh: 2345",
      nickLabel: "Nickname akun (opsional)",
      nickPh: "nickname in-game",
      sellerLabel: "Nama penjual / toko (opsional)",
      sellerPh: "contoh: Store ABC",
      sellerContactLabel: "Kontak penjual (opsional)",
      sellerContactPh: "WA / IG / Discord penjual",
      typeLabel: "Jenis masalah",
      descLabel: "Kronologi kejadian",
      descPh: "Ceritakan apa yang terjadi: kapan beli, dari siapa, kenapa akun bermasalah...",
      evidenceLabel: "Link bukti — screenshot / chat (opsional)",
      evidencePh: "https://...",
      reporterLabel: "Namamu",
      reporterPh: "Nama atau nickname",
      reporterContactLabel: "WhatsApp kamu (opsional, tidak dipajang)",
      reporterContactPh: "08xxxxxxxxxx",
      submit: "Kirim laporan",
      submitting: "Mengirim laporan...",
      successTitle: "Laporan terkirim!",
      successDesc: "Terima kasih sudah melindungi pembeli lain. Laporanmu akan tampil di daftar setelah diverifikasi admin.",
      successBack: "Lihat daftar akun bermasalah",
      privacy: "Nama dan kontakmu tidak dipajang di halaman publik — hanya dipakai admin untuk verifikasi.",
    },
    errors: {
      nameWaRequired: "Nama dan nomor WhatsApp wajib diisi.",
      accountGone: "Akun baru saja disewa orang lain. Pilih akun lain, ya.",
      pkgNotFound: "Paket tidak ditemukan. Muat ulang halaman lalu coba lagi.",
      noUsdPrice: "Paket ini belum punya harga luar negeri (USD). Pilih mata uang Rupiah atau paket lain.",
      couponInvalid: "Kode voucher tidak ditemukan atau sudah nonaktif. Hapus kodenya atau pakai kode lain.",
      regRequired: "Nama, email, dan password wajib diisi.",
      emailInvalid: "Format email tidak valid.",
      passMin: "Password minimal 6 karakter.",
      passMismatch: "Konfirmasi password tidak cocok.",
      emailTaken: "Email sudah terdaftar. Silakan masuk.",
      loginRequired: "Email dan password wajib diisi.",
      loginFailed: "Email atau password salah.",
      cryptoOff: "Pembayaran crypto belum tersedia. Silakan bayar via QRIS/VA.",
      cryptoFail: "Gagal membuat invoice crypto. Coba lagi atau bayar via QRIS/VA.",
      mkInactive: "Akun marketer ini sedang nonaktif. Hubungi admin.",
      couponMin: "Kode kupon minimal 3 karakter (huruf/angka/strip).",
      couponTaken: "Kode {code} sudah dipakai. Coba kode lain.",
      reportRequired: "ID akun, kronologi kejadian, dan namamu wajib diisi.",
      reportDetail: "Ceritakan kronologi minimal 20 karakter agar laporanmu bisa diverifikasi.",
      reportType: "Jenis masalah tidak valid.",
      reportEvidence: "Link bukti harus diawali http:// atau https://.",
    },
  },

  en: {
    common: {
      copy: "Copy",
      copied: "Copied",
    },
    header: {
      catalog: "Catalog",
      howTo: "How to Rent",
      reports: "Blacklist",
      login: "Sign in",
      rentNow: "Rent now",
      rent: "Rent",
    },
    footer: {
      tagline: "Online Mobile Legends account rental. Open 24 hours, every day.",
      contact: "Contact",
      reports: "Blacklist",
      disclaimer:
        "Rentzo is not affiliated with Moonton. Mobile Legends and all related trademarks belong to their respective owners.",
    },
    home: {
      available: "{n} accounts ready to play",
      heroTitle1: "Pick an account.",
      heroTitle2: "Play right away.",
      heroSummary:
        "Rent high-rank, full-skin Mobile Legends accounts. Fast process, secure accounts, undivided playtime.",
      seeAll: "View all accounts",
      howTo: "How to rent",
      ready: "Ready",
      rented: "Rented",
      heroesSkins: "{heroes} heroes / {skins} skins",
      perHour: "/hour",
      emptyDeck: "Account catalog coming soon.",
      collectionEyebrow: "The Rentzo collection",
      catalogTitle: "Account catalog",
      catalogDesc:
        "Every account is checked by our admin before being listed. The account email and password become visible once your payment is confirmed.",
      liveNow: "{n} LIVE now",
      howEyebrow: "Get started",
      howTitle: "How to Rent",
      howDesc: "Three steps, usually done in under five minutes.",
      steps: [
        { title: "Pick an account", desc: "Browse the catalog, check the rank, skins, and price. All info is written as-is." },
        { title: "Pay", desc: "Fill in the rental form, transfer the total, then send the receipt to the admin via Telegram." },
        { title: "Log in & play", desc: "Once your payment is confirmed, the account email and password appear on the order page." },
      ],
      serviceTitle: "More than a safety promise.",
      serviceDesc: "These are the rules we enforce on every account and every rental session.",
      perks: [
        { metric: "100%", title: "Playtime stays whole", desc: "Can't log in or account trouble? Any lost duration is fully compensated." },
        { metric: "Ours", title: "Not consigned accounts", desc: "Every account is managed directly by Rentzo. No stolen accounts, phishing, or shady sources." },
        { metric: "<5 min", title: "Admins actually respond", desc: "Support is available 24/7 with an average reply under five minutes." },
        { metric: "1 : 1", title: "No session sharing", desc: "One account for one renter. The password is always changed after the rental ends." },
      ],
      ctaTitle: "Want to play today?",
      ctaDesc: "Weekend slots run out fast. Secure your account now and pay after dealing with the admin.",
      ctaBtn: "Chat admin now",
      ctaWa: "Hi admin, I want to rent a Mobile Legends account today",
    },
    card: {
      subtitle: "Mobile Legends account rental",
      from: "From",
      perHour: "per hour",
      available: "Available",
      rented: "Rented",
      heroes: "{n} heroes",
      skins: "{n} skins",
      rent: "Rent",
      rentedBtn: "Rented",
      viewDetail: "View {title} details",
    },
    showcase: {
      aria: "Rental account picks",
      kickerReady: "ACCOUNT AVAILABLE NOW",
      kickerRented: "ACCOUNT CURRENTLY RENTED",
      desc: "Rank {rank} with {heroes} heroes and {skins} skins. Ready for pushing rank and playing with friends.",
      rankFallback: "high",
      perHour: "/ hour",
      rent: "Rent account",
      detail: "View details",
      available: "Available",
      rented: "Rented",
      perHourShort: "/hour",
      showAccount: "Show {title}",
    },
    filter: {
      title: "Filter by rank",
      all: "All",
      found: "{n} accounts found",
      live: "LIVE now",
      offline: "Offline",
      empty: "No accounts in this category yet. Try another category or chat with the admin.",
      groupLabel: "Filter by rank",
    },
    akun: {
      home: "Home",
      catalog: "Catalog",
      noPreview: "Preview not available yet",
      aboutEyebrow: "About this account",
      aboutTitle: "What you get",
      defaultDesc: "Full account information has been verified by the admin before being listed in the catalog.",
      feature1: "Private login details",
      feature2: "Checked before rental",
      feature3: "Login-issue guarantee",
      dossier: "Account dossier",
      rankNow: "Current rank",
      heroesAvail: "Heroes available",
      skinColl: "Skin collection",
      accLevel: "Account level",
      from: "From",
      perHour: "/hour",
      minHours: "Min. 1 hour",
      maxHours: "Max. 72 hours",
      bookingNote:
        "Login details appear after payment is confirmed. Only you hold the account for the whole rental.",
      rentThis: "Rent this account",
      rentedBtn: "Currently rented",
      rentedNote:
        "This account is being used by another renter. Check other accounts in the catalog or ask the admin for availability.",
      tierLabel: "Account tier",
    },
    sewa: {
      title: "Rental form",
      sub: "Fill in the details below, then you'll get an order code for payment.",
      rentedTitle: "Account currently rented",
      rentedDesc: "{title} is being used by another renter. Pick another available account.",
      back: "Back to catalog",
    },
    checkout: {
      name: "Your name",
      namePh: "e.g. Raka",
      wa: "Active WhatsApp number",
      waPh: "e.g. 081234567890",
      voucher: "Marketer voucher code (optional)",
      voucherPh: "e.g. RAKA10",
      voucherHint: "Have a marketer coupon? Enter it here for a free +{days}-day rental extension.",
      noAccount: "No account yet?",
      register: "Sign up",
      noAccountTail: "so your orders are saved in your profile.",
      duration: "Choose rental duration",
      currency: "Choose currency",
      curIdr: "Rupiah (Rp)",
      curUsd: "Dollar (USD)",
      curUsdHint: "For international buyers. Payment is done via crypto (BTC, USDT, etc.).",
      usdUnavailable: "Not available (USD)",
      curPayNote: "This order is paid via crypto in USD.",
      perHour: "Per hour",
      perHourUnit: "/hour",
      hoursAria: "Rental duration in hours",
      hoursHint: "Minimum 1 hour, maximum 72 hours.",
      package: "{label} package",
      save: "save {amount}",
      total: "Total",
      submit: "Create order",
      submitting: "Creating order...",
      hours: "{n} hours",
      days: "{n} days",
      weeks: "{n} weeks",
    },
    order: {
      codeLabel: "Order code",
      account: "Account",
      renter: "Renter",
      duration: "Duration",
      created: "Created",
      total: "Total",
      pkg: "{label} package",
      hours: "{n} hours",
      bonusLine: "+{days} days bonus from coupon {code}",
      pendingTitle: "Complete your payment",
      pendingDesc:
        "Pay via QRIS or bank virtual account. Once the payment succeeds, the account email and password automatically appear on this page.",
      pendingUsdDesc:
        "Pay via crypto (BTC, USDT, etc.) in USD. Once the payment succeeds, the account email and password automatically appear on this page.",
      pay: "Pay {total}",
      cryptoPay: "Pay with Crypto (BTC, USDT, etc.)",
      cryptoLoading: "Preparing crypto invoice...",
      autoCheck:
        "Status is checked automatically every few seconds — this page updates by itself once your payment is confirmed.",
      processedPakasir: "Payments are processed by Pakasir.",
      processedBoth: "Payments are processed by Pakasir or OxaPay.",
      needHelp: "Need help?",
      chatAdmin: "Chat admin",
      waIssue: "Hi admin, I have a payment issue with order {code}",
      paidTitle: "Your account is ready",
      paidDesc:
        "Log in with the details below. The {duration} duration counts from the moment you log in. Do not change the account password.",
      paidBonus: "Coupon {code} applied — your rental period is extended by {days} days for free.",
      emailAcc: "Account email",
      password: "Password",
      contactAdmin: "Contact admin",
      loginIssue: "Trouble logging in?",
      waLogin: "Hi admin, I have a login issue with order {code}",
      doneTitle: "Rental finished",
      doneDesc: "Thanks for renting at Rentzo. The account has been secured again.",
      rentAgain: "Rent again",
      cancelTitle: "Order cancelled",
      cancelDesc: "This order is inactive. If you think this is a mistake, contact the admin.",
      askAdmin: "Ask admin",
      waCancel: "Hi admin, I want to ask about my cancelled order {code}",
      durationPkg: "{label} package",
      bonusConcat: " + {days}-day bonus from coupon {code}",
      remaining: "Time remaining",
      remainingEnded: "The rental period has ended",
      remainingUntil: "Ends {date}",
    },
    profil: {
      hello: "Hi, {name}!",
      sub: "This is your Rentzo account.",
      logout: "Sign out",
      name: "Name",
      email: "Email",
      wa: "WhatsApp",
      since: "Member since",
      explore: "Browse the catalog & rent an account",
      history: "Order history",
      empty: "You have no orders yet. Start your first rental from the catalog.",
      thCode: "Code",
      thAccount: "Account",
      thDuration: "Duration",
      thTotal: "Total",
      thStatus: "Status",
      pkg: "{label} package",
      hours: "{n} hours",
      bonus: "+{days} days coupon {code}",
      sisa: "{value} left",
    },
    auth: {
      eyebrow: "Your playground awaits",
      title: "Play without limits.",
      summary: "Sign in to Rentzo to continue your rental sessions, view orders, and access the accounts you're renting.",
      trust1: "Verified accounts",
      trust2: "Secure login data",
      notMember: "NOT A MEMBER?",
      register: "Sign up",
      welcome: "Welcome back",
      loginTitle: "Sign in to your account",
      loginSub: "Continue your adventure in the Land of Dawn.",
      email: "Email",
      emailPh: "name@email.com",
      password: "Password",
      passwordPh: "Enter your password",
      loginBtn: "Sign in to Rentzo",
      checking: "Checking...",
      caption: "By signing in, you agree to the use of Rentzo's services.",
      regTitle: "Create account",
      regSub: "Sign up free to rent accounts on Rentzo.",
      haveAccount: "Already have an account?",
      loginHere: "Sign in",
      loginHereLong: "Sign in here",
      name: "Name",
      namePh: "Full name or nickname",
      regEmailPh: "you@example.com",
      wa: "WhatsApp number",
      passMinPh: "Minimum 6 characters",
      confirm: "Repeat password",
      confirmPh: "Re-type your password",
      regBtn: "Sign up",
      regLoading: "Signing up...",
    },
    marketer: {
      loginTitle: "Marketer area",
      loginSub: "Sign in to track your coupon performance. No account yet? Ask the admin to register you.",
      loginBtn: "Sign in to dashboard",
      hello: "Hi, {name}!",
      sub: "Track your coupon performance and create new codes anytime.",
      logout: "Sign out",
      statActive: "Active coupons",
      statUsed: "Total coupon usage",
      statBonus: "Bonus per use",
      bonusDaysValue: "+{days} days",
      statCommission: "My commission",
      statCommissionUsd: "Dollar commission",
      createTitle: "Create a new coupon code",
      createDesc:
        "Every renter who enters your code at checkout gets a free +{days}-day rental extension. Share your code in content, WA status, or directly to friends.",
      createPh: "e.g. RAKASAVE — leave empty for a random code",
      createBtn: "Create coupon",
      creating: "Creating...",
      yourCoupons: "Your coupons",
      noCoupons: "You have no coupons yet. Create your first code above.",
      active: "Active",
      inactive: "Inactive",
      createdAt: "Created {date}",
      usedTimes: "used {n}x",
      deactivate: "Deactivate",
      activate: "Activate",
      delete: "Delete",
      deleteMsg: "Delete coupon {code}? This code can no longer be used by renters. Usage history stays saved.",
      usageTitle: "Accounts rented with your coupon",
      noUsage: "No renter has used your coupon yet.",
      thOrder: "Order code",
      thAccount: "Account rented",
      thCoupon: "Coupon",
      thBonus: "Bonus",
      thStatus: "Status",
      thCommission: "Commission",
    },
    status: {
      ready: "LIVE · Available",
      rented: "Rented",
      maintenance: "Maintenance",
      pending: "Awaiting payment",
      paid: "Paid",
      done: "Done",
      cancelled: "Cancelled",
    },
    reports: {
      eyebrow: "A warning for account buyers",
      title: "Problem account blacklist",
      desc: "Accounts reported for hackback, password changes, or scams by real buyers. Check an account ID here before buying from anyone.",
      statsTotal: "Total reports",
      statsVerified: "Verified",
      statsPending: "Awaiting verification",
      searchLabel: "Search account ID, nickname, or seller",
      searchPh: "e.g. 123456789",
      filterAll: "All cases",
      typeHackback: "Hackback",
      typePassword: "Password changed",
      typeScam: "Scam",
      typeOther: "Other",
      found: "{n} reports",
      empty: "No matching reports. Try another keyword or filter.",
      emptyAll: "No verified reports yet. If you've been scammed, be the first to report it.",
      accountId: "Account ID",
      server: "Server",
      nickname: "Nickname",
      seller: "Seller",
      sellerContact: "Seller contact",
      game: "Game",
      evidence: "View evidence",
      reportedAt: "Reported {date}",
      ctaTitle: "Got hit by a hackback?",
      ctaDesc: "Share your story so other buyers don't become the next victim. Reports appear on the list after an admin check.",
      ctaBtn: "Report an account now",
      formTitle: "Report a problem account",
      formSub: "Fill in what you know about the account. Every report is checked by an admin before being listed.",
      gameLabel: "Account game",
      idLabel: "In-game account ID",
      idPh: "e.g. 123456789",
      zoneLabel: "Server / Zone ID (optional)",
      zonePh: "e.g. 2345",
      nickLabel: "Account nickname (optional)",
      nickPh: "in-game nickname",
      sellerLabel: "Seller / store name (optional)",
      sellerPh: "e.g. Store ABC",
      sellerContactLabel: "Seller contact (optional)",
      sellerContactPh: "Seller's WA / IG / Discord",
      typeLabel: "Problem type",
      descLabel: "What happened",
      descPh: "Tell us what happened: when you bought it, from whom, and how the account went wrong...",
      evidenceLabel: "Evidence link — screenshot / chat (optional)",
      evidencePh: "https://...",
      reporterLabel: "Your name",
      reporterPh: "Name or nickname",
      reporterContactLabel: "Your WhatsApp (optional, never shown publicly)",
      reporterContactPh: "08xxxxxxxxxx",
      submit: "Send report",
      submitting: "Sending report...",
      successTitle: "Report sent!",
      successDesc: "Thanks for protecting other buyers. Your report will appear on the list once verified by an admin.",
      successBack: "View the problem account list",
      privacy: "Your name and contact are never shown publicly — only used by the admin for verification.",
    },
    errors: {
      nameWaRequired: "Name and WhatsApp number are required.",
      accountGone: "This account was just rented by someone else. Please pick another one.",
      pkgNotFound: "Package not found. Reload the page and try again.",
      noUsdPrice: "This package has no international (USD) price yet. Choose Rupiah or another package.",
      couponInvalid: "Voucher code not found or inactive. Remove it or use another code.",
      regRequired: "Name, email, and password are required.",
      emailInvalid: "Invalid email format.",
      passMin: "Password must be at least 6 characters.",
      passMismatch: "Password confirmation does not match.",
      emailTaken: "This email is already registered. Please sign in.",
      loginRequired: "Email and password are required.",
      loginFailed: "Wrong email or password.",
      cryptoOff: "Crypto payment is not available yet. Please pay via QRIS/VA.",
      cryptoFail: "Failed to create a crypto invoice. Try again or pay via QRIS/VA.",
      mkInactive: "This marketer account is currently inactive. Contact the admin.",
      couponMin: "Coupon code needs at least 3 characters (letters/numbers/dash).",
      couponTaken: "Code {code} is already taken. Try another one.",
      reportRequired: "Account ID, the story, and your name are required.",
      reportDetail: "Describe what happened in at least 20 characters so your report can be verified.",
      reportType: "Invalid problem type.",
      reportEvidence: "Evidence link must start with http:// or https://.",
    },
  },
};
